#!/usr/bin/env zsh

export EDITOR=nvim
export PAGER=bat
# Set the XDG standard config directory location
export XDG_CONFIG_HOME=$HOME/.config
# Set the XDG standard data directory location
export XDG_DATA_HOME=$HOME/.local/share
# Allow fzf to include hidden files except for those
# explicitly ignored. This will be used in vim as well.
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""' 

# Set to vi mode
bindkey -v
# From: http://stratus3d.com/blog/2017/10/26/better-vi-mode-in-zshell/
# `v` is already mapped to visual mode, so we need to use a different key to open Vim
bindkey -M vicmd "^V" edit-command-line

# Enable case-insensitive searching and colors
export LESS="iR"

init_powerline() {
  if [ -z $DISABLE_POWERLINE ]; then
    REPOSITORY_ROOT=/usr/local/lib/python3.8/site-packages
    source $REPOSITORY_ROOT/powerline/bindings/zsh/powerline.zsh
  fi
}

init_powerline

# direnv hook
eval "$(direnv hook zsh)"
