#!/usr/bin/env zsh

export EDITOR=vi
export PAGER=less
# Set the XDG standard config directory location
export XDG_CONFIG_HOME=$HOME/.config
# Set the XDG standard data directory location
export XDG_DATA_HOME=$HOME/.local/share

# Set to vi mode
bindkey -v

# Enable case-insensitive searching and colors
export LESS="iR"

init_powerline() {
  if [ -z $DISABLE_POWERLINE ]; then
    REPOSITORY_ROOT=/usr/local/lib/python3.8/site-packages
    source $REPOSITORY_ROOT/powerline/bindings/zsh/powerline.zsh
  fi
}

init_powerline

# direnv hook
eval "$(direnv hook zsh)"
